spring.application.name=restaurante
spring.datasource.url=jdbc:postgresql://localhost:5432/localhost
spring.datasource.username=admin
spring.datasource.password=12345
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect